name: 'CI Dokumentor'
description: 'Automatically generate documentation for CI/CD components like GitHub Actions and workflows'
author: hoverkraft
branding:
  icon: 'book-open'
  color: 'blue'

inputs:
  source:
    description: 'Source manifest file path to handle (e.g. `action.yml`, `.github/workflows/ci.yml`).'
    required: true
  output:
    description: 'Output path for generated documentation (optional; destination is auto-detected if not specified by the adapter).'
    required: false
  repository:
    description: 'Repository platform (auto-detected if not specified).'
    required: false
  cicd:
    description: 'CI/CD platform (github-actions, gitlab-ci, etc.).'
    required: false
  include-sections:
    description: 'Comma-separated list of sections to include.'
    required: false
  exclude-sections:
    description: 'Comma-separated list of sections to exclude.'
    required: false
  version:
    description: 'Version of CI Dokumentor to use. See <https://github.com/hoverkraft-tech/ci-dokumentor/releases>.'
    required: false
    default: 'latest'

runs:
  using: 'composite'
  steps:
    - shell: bash
      run: |
        args="generate --source '${{ inputs.source }}' --output '${{ inputs.output }}'"
        if [ -n "${{ inputs.repository }}" ]; then
          args="$args --repository '${{ inputs.repository }}'"
        fi
        if [ -n "${{ inputs.cicd }}" ]; then
          args="$args --cicd '${{ inputs.cicd }}'"
        fi
        if [ -n "${{ inputs.include-sections }}" ]; then
          args="$args --include-sections '${{ inputs.include-sections }}'"
        fi
        if [ -n "${{ inputs.exclude-sections }}" ]; then
          args="$args --exclude-sections '${{ inputs.exclude-sections }}'"
        fi
        docker run --rm -v "$PWD:/workspace" -w /workspace ghcr.io/hoverkraft-tech/ci-dokumentor/cli:${{ inputs.version }} $args
