version: '3.8'

services:
  ci-dokumentor:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    image: ci-dokumentor:latest
    container_name: ci-dokumentor
    volumes:
      # Mount current directory to /workspace for file access
      - .:/workspace:ro
      # Mount output directory for generated documentation
      - ./docs:/output
    working_dir: /workspace
    # Default command - can be overridden
    command: ["node", "packages/cli/dist/bin/ci-dokumentor.js", "--help"]
    # Uncomment to keep container running for debugging
    # tty: true
    # stdin_open: true
    
  # Service for development/testing with shell access
  ci-dokumentor-dev:
    build:
      context: .
      dockerfile: docker/Dockerfile
      target: production
    image: ci-dokumentor:latest
    container_name: ci-dokumentor-dev
    volumes:
      - .:/workspace
    working_dir: /workspace
    entrypoint: ["/bin/sh"]
    tty: true
    stdin_open: true
    
# Optional: Create a network for isolation
networks:
  default:
    name: ci-dokumentor-network