import { ReadableContent } from '../../reader/readable-content.js';
import { SectionGenerationPayload, SectionIdentifier } from './section-generator.adapter.js';

/**
 * Base class for Generated section generator.
 * This section adds attribution to CI Dokumentor at the end of documentation.
 * The implementation is platform-agnostic.
 */
export class AbstractGeneratedSectionGenerator<TManifest> {
  getSectionIdentifier(): SectionIdentifier {
    return SectionIdentifier.Generated;
  }

  async generateSection({ formatterAdapter }: SectionGenerationPayload<TManifest>): Promise<ReadableContent> {
    const generatedText = 'This documentation was automatically generated by [CI Dokumentor](https://github.com/hoverkraft-tech/ci-dokumentor).';

    return formatterAdapter.horizontalRule().append(
      formatterAdapter.lineBreak(),
      formatterAdapter.paragraph(new ReadableContent(generatedText)),
    );
  }
}
