import { SectionGenerationPayload } from '@ci-dokumentor/core';
import { GitHubActionsManifest } from '../github-actions-parser.js';
import { GitHubActionsSectionGeneratorAdapter } from './github-actions-section-generator.adapter.js';
import { SectionIdentifier } from '@ci-dokumentor/core';
import { injectable } from 'inversify';

@injectable()
export class GeneratedSectionGenerator extends GitHubActionsSectionGeneratorAdapter {
  getSectionIdentifier(): SectionIdentifier {
    return SectionIdentifier.Generated;
  }

  async generateSection({ formatterAdapter }: SectionGenerationPayload<GitHubActionsManifest>): Promise<Buffer> {
    const generatedText = 'This documentation was automatically generated by [CI Dokumentor](https://github.com/hoverkraft-tech/ci-dokumentor).';

    return Buffer.concat([
      formatterAdapter.horizontalRule(),
      formatterAdapter.lineBreak(),
      formatterAdapter.paragraph(Buffer.from(generatedText)),
    ]);
  }
}