import { ReadableContent, SectionIdentifier } from '@ci-dokumentor/core';
import type { SectionGenerationPayload } from '@ci-dokumentor/core';
import { injectable } from 'inversify';
import { GitHubActionsManifest } from '../github-actions-parser.js';
import { GitHubActionsSectionGeneratorAdapter } from './github-actions-section-generator.adapter.js';

@injectable()
export class GeneratedSectionGenerator extends GitHubActionsSectionGeneratorAdapter {
  getSectionIdentifier(): SectionIdentifier {
    return SectionIdentifier.Generated;
  }

  async generateSection({ formatterAdapter }: SectionGenerationPayload<GitHubActionsManifest>): Promise<ReadableContent> {
    const generatedText = 'This documentation was automatically generated by [CI Dokumentor](https://github.com/hoverkraft-tech/ci-dokumentor).';

    return formatterAdapter.horizontalRule().append(
      formatterAdapter.lineBreak(),
      formatterAdapter.paragraph(new ReadableContent(generatedText)),
    );
  }
}