name: Docker build images

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  merge_group:

permissions:
  contents: read
  issues: read
  packages: write
  pull-requests: read
  id-token: write

jobs:
  docker-build-images:
    uses: hoverkraft-tech/ci-github-container/.github/workflows/docker-build-images.yml@0.26.0
    secrets:
      # Password or GitHub token (packages:read and packages:write scopes) used to log against the OCI registry.
      oci-registry-password: ${{ secrets.GITHUB_TOKEN }}
      
      # List of secrets to expose to the build.
      build-secrets: ""
      
      # GitHub App private key to generate GitHub token to be passed as build secret env.
      build-secret-github-app-private-key: ""
      
      # Build secrets environment variables from outputs of github-app-token action.
      build-secret-envs: ""
      
      # GitHub App ID to generate GitHub token to be passed as build secret env.
      build-secret-github-app-id: ""
      
      # The owner of the GitHub App installation.
      build-secret-github-app-owner: ${{ github.repository_owner }}
    with:
      images: |
        [
          {
            "name": "ci-dokumentor",
            "context": ".",
            "dockerfile": "docker/Dockerfile",
            "target": "production",
            "platforms": [
              "linux/amd64",
              "linux/arm64"
            ]
          }
        ]