name: Pull request - Continuous Integration

on:
  merge_group:
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  packages: read
  statuses: write
  security-events: write
  id-token: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/__shared-ci.yml
    secrets: inherit

  docs-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: 'website/package-lock.json'

      - name: Install documentation dependencies
        run: |
          cd website
          npm ci

      - name: Build documentation
        run: |
          cd website
          npm run build

      - name: Upload documentation artifacts
        uses: actions/upload-artifact@v4
        with:
          name: documentation-build
          path: website/build/
