---
name: Pull request - Continuous Integration

on:
  merge_group:
  pull_request:
    branches: [main]

permissions:
  actions: read
  contents: read
  id-token: write
  issues: read
  packages: write
  pull-requests: read
  security-events: write
  statuses: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  ci:
    uses: ./.github/workflows/__shared-ci.yml
    secrets: inherit
    with:
      sign-images: false
